### ISSUE TITLE
How to create MOTD

### ISSUE THREAD

**Issue by ice2921** [UnimatrixZeroOne/BibleBot#64]
Is it possible to have the bot quote random verses throughout a certain time interval?

**Comment by vypr** [comment]
Yes, however the implications that come with that may not make the feature worthwhile. It would be too overkill to create a new database solely for this (which would have to be done), give people the ability to enable/disable it for their server (which would require that BibleBot have staff permissions above the highest role, in order to see the permissions of whoever wrote the message), and if I had it force-enabled, I can only imagine the amount of pings I'd get from server owners complaining about it.

Given that you're looking for a verse of the day, but maybe a bit more regular, `+votd` (or `+verseoftheday` or whatever your selected language's equivalent is) should hold you over for the time being.

I'll take a look into this, I won't make any sort of yes or no "I will do this", but at the very least I could make this an option for those who self-host.

**Comment by ice2921** [comment]
Ok thanks.
